---

- name: create locale grub dir
  file:
    path: /boot/grub/locale
    state: directory

- name: copy de locale grub
  copy:
    src: /usr/share/locale/de/LC_MESSAGES/grub.mo
    dest: /boot/grub/locale/de.gmo

- name: configure grub
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX=.*'
    line: 'GRUB_CMDLINE_LINUX="{{cmdline}}"'
    state: present
