---
- name: Upgrade pacman cache
  pacman:
    update_cache: yes

- name: install desktop packages
  pacman:
    name:
      - sway
      - swaybg
      - xorg-server-xwayland
      - waybar
      - dunst
      - mako # notification daemon
      - kanshi # autorandr for wayland
      - grim # screenshots
      - slurp # region selector
      - wl-clipboard # clipboard manager
      - brightnessctl # brightness manager
      - swayidle
      - xdg-user-dirs
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - lib32-virtualgl
      - vulkan-intel
      - lib32-vulkan-intel
      - libva-intel-driver
      - libva-utils
      - xf86-video-intel
    state: present

- name: install audio packages
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present

- name: install applications packages
  pacman:
    name:
      - imv # img visualizer
      - kitty # terminal emulator
      - code # code editor
      - zathura # pdf viewer
      - firefox-developer-edition
      - gimp # img editor
      - mpd # music player
      - lxappearance # theme manager
      - mpv # video player
      - thunar # file manager
      - openvpn
      - playerctl # music player cli controller
      - qbittorrent # torrent downloader
      - texlive-bin # latex
      - texlive-core # latex
      - texlive-latexextra # latex
      - papirus-icon-theme # icon theme
      - youtube-dl
      - ansible
      - arc-gtk-theme
      - audacity
      - autossh
      - bash-completion
      - bemenu-wlroots
      - blender
      - borg
      - chromium
      - cmake
      - cmatrix
      - code
      - conky
      - coreutils
      - cronie
      - cryptsetup
      - distcc
      - dunst
      - feh
      - figlet
      - gparted
      - homebank
      - keepassxc
      - kdiff3
      - krita
      - kdenlive
      - lsd
      - mitmproxy
      - ncmpcpp
      - networkmanager
      - ntfs-3g
      - playerctl
      - qiv
      - qemu
      - rofi
      - signal-desktop
      - streamlink
      - syncthing
      - syncthing-gtk
      - telegram-desktop
      - thunderbird
      - tmux
      - torsocks
      - ttf-font-awesome
      - udiskie
      - unicode-emoji
      - unrar
      - veracrypt
      - virt-manager
      - vnstat
      - weechat
      - wl-clipboard
      - wofi
      - zsh
      - meson
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv '{{item}}'
  loop:
    - 4773BD5E130D1D45 # spotify

  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - ddccontrol
      - downgrade
      - freefilesync
      - homesick
      - jetbrains-toolbox
      - mpdas
      - mpdris2
      - pikaur
      - postman
      - pulseaudio-ctl
      - spotify
      - thinkfan
      - zola-bin
    #  - nordic-theme-git # Endless install
