---
- name: create networkmanager dispatcher dir
  file:
    path: /etc/NetworkManager/dispatcher.d/
    state: directory

- name: enable user based scripts for networkmanager
  copy:
      src: 99-user-scripts
      dest: /etc/NetworkManager/dispatcher.d/99-user-scripts
      owner: root
      group: root
      mode: '0744'
      backup: yes

- name: enable vnstat
  systemd:
    name: vnstat
    state: restarted
    enabled: yes

- name: enable networkmanager
  systemd:
    name: NetworkManager
    state: restarted
    enabled: yes
