---
- name: enable user based scripts for networkmanager
  copy:
      src: 99-user-scripts
      dest: /etc/NetworkManager/dispatcher.d/99-user-scripts
      owner: root
      group: root
      mode: '0744'
      backup: yes

- name: enable vnstat
  systemd:
    name: vnstat
    state: restart
    enabled: yes
