---
- hosts: all
  become: yes

  vars:
    user: x
    shell: /usr/bin/zsh
    cmdline: ""
    veracrypt_serials: 
      - x
    usb_ignore_serials:
      - x
    network_mounts:
      - name: x
        password: x
        username: x
        path: x
        mount: x
        options: x


  pre_tasks:

    # Fix full /tmp when installing lots of AUR
    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

    - name: include guest role
      tags: guest
      include_role:
        name: guest
      when: ansible_virtualization_role == "guest"

  roles:
    - { role: udisks, tags: udisks}
    - { role: network-shares, tags: networkshares}
    - { role: networkmanager, tags: networkmanager}
    - { role: veracrypt-auto-mount, tags: veracrypt}
    - { role: pacman, tags: pacman }
    - { role: aur, tags: aur }
    - { role: btrfs/packages, tags: btrfs }
    - { role: btrfs/snapper, tags: snapper }
    - { role: base, tags: base }
    - { role: desktop, tags: desktop }
    - { role: virtualization, tags: virtualization }
    # - { role: containers, tags: containers }
    # - { role: recovery, tags: recovery }
    - { role: btrfs/grub, tags: boot }
    - { role: btrfs/initramfs, tags: boot }
